# Generated by Django 4.2.2 on 2023-07-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_alter_review_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
