# Generated by Django 4.2.2 on 2023-07-04 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("universities", "0006_alter_review_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="users_like",
            field=models.ManyToManyField(
                blank=True, related_name="images_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
