# Generated by Django 4.2.2 on 2023-07-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0008_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=3000)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="universities.comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "CommentReport",
                "verbose_name_plural": "CommentReports",
            },
        ),
    ]
