# Generated by Django 4.2.2 on 2023-09-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "universities",
            "0011_comment_active_commentreport_active_review_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewhistory",
            name="title",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
