# Generated by Django 4.2.2 on 2023-09-28 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0012_alter_reviewhistory_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commenthistory",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="universities.comment",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="reviewhistory",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="universities.review"
            ),
        ),
        migrations.AlterField(
            model_name="reviewhistory",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
