# Generated by Django 4.2.2 on 2023-09-28 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0015_alter_commenthistory_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commenthistory",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="universities.comment",
            ),
        ),
        migrations.AlterField(
            model_name="reviewhistory",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="universities.review",
            ),
        ),
    ]
